#!/usr/bin/env bash

set -x

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="10"
gaps["bottom"]="10"
gaps["left"]="10"
gaps["right"]="10"
gaps["inner"]="10"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# ===== Tiling setting =========================

yabai -m config layout                      float

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

yabai -m config window_opacity off 
yabai -m config active_window_opacity 0.95
yabai -m config normal_window_opacity 0.92

yabai -m config window_border               off
yabai -m config window_border_width         5
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config split_ratio                 0.50

yabai -m config auto_balance                on

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Rules ==================================

yabai -m rule --add title='.*Preferences*.|.*设置*.'  manage=off

yabai -m rule --add app="^IntelliJ IDEA$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="( – )" manage=on
# yabai -m rule --add app="Intellij IDEA" title='.*Welcome*.|Checkout*.|.*Configurations|Choose*.|Import*.|.*Charges|Tip*.|Rename*.|Preferences|.*New*.|Run*.|' manage=off
# yabai -m rule --add app="IntelliJ IDEA|CLion|GoLand" title='.*Welcome*.|.*Run*.|.*Project*.|.*Merge*.|Rename*.|Preferences|Licenses|.*New*.|.*Class*.|.*Move*.|Breakpoints|.*Improt*.|.*Open*.|.*Tip*.'  manage=off

# 临时性的App 也就是manage=off不受到yabai平铺式的限制，之前怎么弹出来就怎么弹出来
manageOffApp='^(Finder|.*Preferences|App Store|Activity Monitor|DBngin|Calculator|Dictionary|IINA|Keka|Software Update|About This Mac|Synology Drive Client|ZenTermLite|TablePlus|WeChat|QQ|Parallels Desktop|Prompt|Preview|Docker Desktop|Microsoft Word|Microsoft Excel|Microsoft PowerPoint)$'
yabai -m rule --add app="${manageOffApp}" manage=off
yabai -m rule --add app="Synology Drive Client" manage=off



set +x
printf "yabai: configuration loaded...\\n"
