#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="10"
gaps["bottom"]="10"
gaps["left"]="10"
gaps["right"]="10"
gaps["inner"]="10"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout                      float

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off 

yabai -m config window_topmost              off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

yabai -m config window_opacity off 
yabai -m config active_window_opacity 0.95
yabai -m config normal_window_opacity 0.92

yabai -m config window_border               off
yabai -m config window_border_width         5
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config split_ratio                 0.50

yabai -m config auto_balance                on

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off 
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="DBngin" app="^DBngin$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="IINA" app="^IINA$" manage=off
yabai -m rule --add label="Keka" app="^Keka$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add title='.*Preferences*.|.*设置*.'  manage=off

# yabai -m rule --add app="Intellij IDEA" title='.*Welcome*.|Checkout*.|.*Configurations|Choose*.|Import*.|.*Charges|Tip*.|Rename*.|Preferences|.*New*.|Run*.|' manage=off 
yabai -m rule --add app="IntelliJ IDEA|CLion" title='.*Welcome*.|.*Run*.|.*Project*.|.*Merge*.|Rename*.|Preferences|Licenses|.*New*.|.*Class*.|.*Move*.|Breakpoints|.*Improt*.|.*Open*.|.*Tip*.'  manage=off
yabai -m rule --add app="ZenTermLite" title='.*Session*.'  manage=off


yabai -m rule --add app="SecureCRT" native-fullscreen=on
yabai -m rule --add app="TablePlus" native-fullscreen=on





yabai -m rule --add app="Parallels Desktop"  manage=off
yabai -m rule --add app="QQ"  manage=off
yabai -m rule --add app="QQ"  manage=off
yabai -m rule --add app="WeChat"  manage=off
yabai -m rule --add app="WeChat"  manage=off

yabai -m rule --add app="Stickies" sticky=on

# 临时性的App 也就是manage=off不受到yabai平铺式的限制，之前怎么弹出来就怎么弹出来
manageOffApp='^(IINA|访达|Calendar|日历|System Preferences|系统偏好设置|1Password 7|Mail|微信|WeChatc|QQ|Android Studio|印象笔记|Stickies|设置)$'
yabai -m rule --add app="${manageOffApp}" manage=off


set +x
printf "yabai: configuration loaded...\\n"
